name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install black
        pip install isort
        pip install pylint
    - name: Lint with black
      run: |
        black --check --line-length 100 .
    - name: Sort imports with isort
      run: |
        isort --check-only --diff .
    - name: Lint with pylint
      run: |
        find . -name \*.py -not -path "./tests/*" | xargs pylint --fail-under=8.5
    - name: Test with pytest
      run: |
        pytest tests/unit/
