name: Python application

on: [push]

jobs:
  commit_gate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
        pip install pytest
        pip install black
        pip install isort
        pip install pylint
        pip install pymongo
        pip install watchdog
        pip install clevercsv
        pip install pandas
    - name: Lint with black
      run: |
        black --check --line-length 100 .
    - name: Sort imports with isort
      run: |
        isort --check-only --diff --skip setup.py .
    - name: Lint with pylint
      run: |
        find . -name \*.py -not -path "./tests/*" | xargs pylint --fail-under=9.0
    - name: Test with pytest
      run: |
        pytest tests/unit/